---
title: '**Homework 3**'
subtitle: |
  | Eco 5316 Time Series Econometrics
  | Spring 2019
  | Due: Saturday, February 9, 11.55pm
urlcolor: magenta
linkcolor: magenta
output:
  pdf_document: default
---

\renewcommand{\baselinestretch}{1.15} \selectfont


## **Problem 1**

Take ["Reporting with R Markdown"](https://www.datacamp.com/courses/reporting-with-r-markdown) course on datacamp.com. 

\bigskip


## **Problem 2**

<!--
Submit your solution for Problem 2 in the form a short report, prepared using R Markdown. Compile the report into a pdf or an html file and upload it to your dropbox folder together with the source Rmd file.
-->

(a) Use `tq_get` to obtain the quarterly real private fixed investment (chain-type quantity index) for the period 1960Q1-2015Q4, available on FRED under code [`B007RA3Q086SBEA`](https://fred.stlouisfed.org/series/B007RA3Q086SBEA).

(b) Construct the log changes in the real private fixed investment $\Delta \log rPFI_t = \log rPFI_t - \log rPFI_{t-1}$ where $rPFI_t$ is the original quarterly real private fixed investment. Plot the time series for $rPFI_t$ and $\Delta \log rPFI_t$ using `ggplot`.

(c) Construct and plot the ACF and the PACF for $\Delta \log rPFI_t$ using `ggAcf` and `ggPacf`. 

(d) Use the ACF and PACF to identify suitable AR and/or MA model(s) and estimate them using `Arima`. 

(e) Perform diagnostics of model(s) from part (d) using `ggtsdiag`. Modify and reestimate the model if needed, if there are several competing specifications use AIC, BIC, Q statistics to compare their properties. 

(f) Use the `auto.arima` function to find the model specification that minimizes AIC and the model specification that minimizes BIC. Again perform the model diagnostics for these two models. 

(g) Summarize your findings.



## **Problem 3**

(a) Use `tq_get` to obtain the monthly industrial production index, available on FRED under code [`INDPRO`](https://fred.stlouisfed.org/series/INDPRO).

(b) Construct the log changes in the industrial production $\Delta \log IP_t = \log IP_t - \log IP_{t-1}$ where $IP_t$ is the original industrial production index. Plot the time series for $IP_t$ and $\Delta \log IP_t$ using `ggplot`.

(c) Follow the same steps as in Problem 2 parts (c)-(g) to find suitable AR/MA/ARMA model(s), this time for $\Delta \log IP_t$.
